<?php

$_COS_LANG_MODULE['locales_timezone_updated'] = 'Tidszone opdateret';
$_COS_LANG_MODULE['locales_timezone_not_valid'] = 'Ikke en gyldig tidszone';
$_COS_LANG_MODULE['locales_timezone_legend'] = 'Vælg tidszone';
$_COS_LANG_MODULE['locales_locale_updated'] = 'Locale opdateret';
$_COS_LANG_MODULE['locales_locale_not_valid'] = 'Local ikke gyldig';
$_COS_LANG_MODULE['locales_set_locale_legend'] = 'Indstil locale - har betydning for navne på bl.a. datoer og penge tegn og forkortelser';
$_COS_LANG_MODULE['locales_language_updated'] = 'Sproget er blevet opdateret';
$_COS_LANG_MODULE['locales_language_not_valid'] = 'Ikke et gydigt sprog';
$_COS_LANG_MODULE['locales_set_language_lengend'] = 'Vælg interface sprog';


$_COS_LANG_MODULE['locales_reload_language'] = 'Opdater oversættelse (hav tålmodighed)';
