<?php


// Translation of file /modules/locales/module.php

$_COS_LANG_MODULE['Timezone has been updated'] = 'Tidszone opdateret';
$_COS_LANG_MODULE['Timezone is not valid'] = 'Ikke en gyldig tidszone';
$_COS_LANG_MODULE['Set timezone for your system'] = 'Vælg tidszone';
$_COS_LANG_MODULE['Locale has been updated'] = 'Sproget er blevet opdateret';
$_COS_LANG_MODULE['Locale is not valid'] = 'Local ikke gyldig';
$_COS_LANG_MODULE['Set locale. Set e.g. dates and money symbols to your language specifics'] = 'Indstil locale - har betydning for navne på bl.a. datoer og penge tegn og forkortelser';
$_COS_LANG_MODULE['Language is not valid'] = 'Ikke et gydigt sprog';
$_COS_LANG_MODULE['Set language of interface and HTML document'] = 'Vælg interface sprog';
$_COS_LANG_MODULE['Update all language files (may take a few minutes)'] = 'Opdater oversættelse (hav tålmodighed)';
