<?php


// Translation of file /modules/locales/module.php

$_COS_LANG_MODULE['Timezone has been updated'] = 'Tidszone opdateret';
$_COS_LANG_MODULE['Timezone is not valid'] = 'Ikke en gyldig tidszone';
$_COS_LANG_MODULE['Set timezone for your system'] = 'Vælg tidszone';
$_COS_LANG_MODULE['Locale has been updated'] = 'Sproget er blevet opdateret';
$_COS_LANG_MODULE['Locale is not valid'] = 'Local ikke gyldig';
$_COS_LANG_MODULE['Set locale. Set e.g. dates and money symbols to your language specifics'] = 'Indstil locale - har betydning for navne på bl.a. datoer og penge tegn og forkortelser';
$_COS_LANG_MODULE['Language is not valid'] = 'Ikke et gydigt sprog';
$_COS_LANG_MODULE['Set language of interface and HTML document'] = 'Vælg interface sprog';
$_COS_LANG_MODULE['Update all language files (may take a few minutes)'] = 'Opdater oversættelse (hav tålmodighed)';

// Translation of file /modules/locales/db.php

$_COS_LANG_MODULE['Her er en lille test'] = 'Her er en lille test';
$_COS_LANG_MODULE['Load language all into DB'] = 'Load language all into DB';
$_COS_LANG_MODULE['submit'] = 'submit';
$_COS_LANG_MODULE['Search and replace in all strings'] = 'Search and replace in all strings';
$_COS_LANG_MODULE['Search string'] = 'Search string';
$_COS_LANG_MODULE['Replace string'] = 'Replace string';
$_COS_LANG_MODULE['Search and replace'] = 'Search and replace';
$_COS_LANG_MODULE['Key'] = 'Nøgle';
$_COS_LANG_MODULE['No translation in'] = 'Ingen oversættelse';
$_COS_LANG_MODULE['Translation in'] = 'Oversættelse i';
$_COS_LANG_MODULE['Update'] = 'Opdater';
$_COS_LANG_MODULE['Edit'] = 'Rediger';

// Translation of file /modules/locales/edit.php

$_COS_LANG_MODULE['Reload language_all files from <span class="notranslate">{template}</span> into DB'] = 'Reload language_all files from <span class="notranslate">{template}</span> into DB';
$_COS_LANG_MODULE['Languages has been reloaded'] = 'Sprog er blevet genindlæst';
$_COS_LANG_MODULE['DB translation has been updated'] = 'DB translation has been updated';
$_COS_LANG_MODULE['No language has been loaded. Presss button to load'] = 'Ingen sprog er indlæst. Presss knappen for at indlæse';
