<?php

$_COS_LANG_MODULE['Current date and time according to setup'] = '根据设置当前日期和时间';
$_COS_LANG_MODULE['Her er en lille test'] = '她呃恩里尔测试';
$_COS_LANG_MODULE['Load language all into DB'] = '负载语言所有到数据库';
$_COS_LANG_MODULE['submit'] = '提交';
$_COS_LANG_MODULE['Search and replace in all strings'] = '搜索和替换所有字符串';
$_COS_LANG_MODULE['Search string'] = '搜索字符串';
$_COS_LANG_MODULE['Replace string'] = '字符串替换';
$_COS_LANG_MODULE['Search and replace'] = '搜索和替换';
$_COS_LANG_MODULE['Key'] = '关键';
$_COS_LANG_MODULE['No translation in'] = '没有翻译';
$_COS_LANG_MODULE['Translation in'] = '在翻译';
$_COS_LANG_MODULE['Update'] = '更新';
$_COS_LANG_MODULE['Edit'] = '编辑';
$_COS_LANG_MODULE['Reload language_all files from <span class="notranslate">{template}</span> into DB'] = '重装language_all文件从<span class="notranslate">{template}</span>到数据库';
$_COS_LANG_MODULE['Languages has been reloaded'] = '语言已重载';
$_COS_LANG_MODULE['DB translation has been updated'] = 'DB翻译呃更新';
$_COS_LANG_MODULE['No language has been loaded. Presss button to load'] = '没有语言已经被加载。 Presss按钮来加载';
$_COS_LANG_MODULE['Timezone has been updated'] = '时区已经更新';
$_COS_LANG_MODULE['Timezone is not valid'] = '时区是无效的';
$_COS_LANG_MODULE['Set timezone for your system'] = '设置时区为你的系统';
$_COS_LANG_MODULE['Locale has been updated'] = '语言环境已更新';
$_COS_LANG_MODULE['Locale is not valid'] = '语言环境是无效的';
$_COS_LANG_MODULE['Set locale. Set e.g. dates and money symbols to your language specifics'] = '设置语言环境。例如：设置日期和金钱符号语言细节';
$_COS_LANG_MODULE['Language is not valid'] = '语言是无效的';
$_COS_LANG_MODULE['Set language of interface and HTML document'] = '接口和HTML文档的语言设置';
$_COS_LANG_MODULE['Update all language files (may take a few minutes)'] = '更新所有语言文件（耐心等待）';
