<?php


// Translation of file /modules/locales/db.php

$_COS_LANG_MODULE['Her er en lille test'] = 'Her er en lille test';
$_COS_LANG_MODULE['Load language all into DB'] = 'Load language all into DB';
$_COS_LANG_MODULE['submit'] = 'submit';
$_COS_LANG_MODULE['Search and replace in all strings'] = 'Search and replace in all strings';
$_COS_LANG_MODULE['Search string'] = 'Search string';
$_COS_LANG_MODULE['Replace string'] = 'Replace string';
$_COS_LANG_MODULE['Search and replace'] = 'Search and replace';
$_COS_LANG_MODULE['Key'] = 'Key';
$_COS_LANG_MODULE['No translation in'] = 'No translation in';
$_COS_LANG_MODULE['Translation in'] = 'Translation in';
$_COS_LANG_MODULE['Update'] = 'Update';
$_COS_LANG_MODULE['Edit'] = 'Edit';

// Translation of file /modules/locales/edit.php

$_COS_LANG_MODULE['Reload language_all files from <span class="notranslate">{template}</span> into DB'] = 'Reload language_all files from <span class="notranslate">{template}</span> into DB';
$_COS_LANG_MODULE['Languages has been reloaded'] = 'Languages has been reloaded';
$_COS_LANG_MODULE['DB translation has been updated'] = 'DB translation er updated';
$_COS_LANG_MODULE['No language has been loaded. Presss button to load'] = 'No language has been loaded. Presss button to load';

// Translation of file /modules/locales/module.php

$_COS_LANG_MODULE['Timezone has been updated'] = 'Timezone has been updated';
$_COS_LANG_MODULE['Timezone is not valid'] = 'Timezone is not valid';
$_COS_LANG_MODULE['Set timezone for your system'] = 'Set timezone for your system';
$_COS_LANG_MODULE['Locale has been updated'] = 'Locale has been updated';
$_COS_LANG_MODULE['Locale is not valid'] = 'Locale is not valid';
$_COS_LANG_MODULE['Set locale. Set e.g. dates and money symbols to your language specifics'] = 'Set locale. Set e.g. dates and money symbols to your language specifics';
$_COS_LANG_MODULE['Language is not valid'] = 'Language is not valid';
$_COS_LANG_MODULE['Set language of interface and HTML document'] = 'Set language of interface and HTML document';
$_COS_LANG_MODULE['Update all language files (may take a few minutes)'] = 'Update all language files (be patient)';
