<?php

$_COS_LANG_MODULE['Timezone has been updated'] = 'Timezone has been updated';
$_COS_LANG_MODULE['Timezone is not valid'] = 'Timezone is not valid';
$_COS_LANG_MODULE['Set timezone for your system'] = 'Set timezone for your system';
$_COS_LANG_MODULE['Locale has been updated'] = 'Locale has been updated';
$_COS_LANG_MODULE['Locale is not valid'] = 'Locale is not valid';
$_COS_LANG_MODULE['Set locale. Set e.g. dates and money symbols to your language specifics'] = 'Set locale. Set e.g. dates and money symbols to your language specifics';
$_COS_LANG_MODULE['Locale has been updated'] = 'Locale has been updated';
$_COS_LANG_MODULE['Language is not valid'] = 'Language is not valid';
$_COS_LANG_MODULE['Set language of interface and HTML document'] = 'Set language of interface and HTML document';


$_COS_LANG_MODULE['Update all language files (may take a few minutes)'] = 'Update all language files (be patient)';
