<?php

$_COS_LANG_MODULE['locales_timezone_updated'] = 'Timezone Updated';
$_COS_LANG_MODULE['locales_timezone_not_valid'] = 'Timezone is not valid';
$_COS_LANG_MODULE['locales_timezone_legend'] = 'Set timezone';
$_COS_LANG_MODULE['locales_locale_updated'] = 'Locale has been updated';
$_COS_LANG_MODULE['locales_locale_not_valid'] = 'Locale is not valid';
$_COS_LANG_MODULE['locales_set_locale_legend'] = 'Set Locale. Set e.g. dates and money symbols to your language specifics';
$_COS_LANG_MODULE['locales_language_updated'] = 'Locales has been updated';
$_COS_LANG_MODULE['locales_language_not_valid'] = 'Language is not valid';
$_COS_LANG_MODULE['locales_set_language_lengend'] = 'Set language of interface and HTML document';


$_COS_LANG_MODULE['locales_reload_language'] = 'Update all language files (be patient)';
