<?php

$_COS_LANG_MODULE['Her er en lille test'] = 'Her er en liten test';
$_COS_LANG_MODULE['Load language all into DB'] = 'Laste språk alle i DB';
$_COS_LANG_MODULE['submit'] = 'sende inn';
$_COS_LANG_MODULE['Search and replace in all strings'] = 'Søk og erstatt i alle strenger';
$_COS_LANG_MODULE['Search string'] = 'Søkestreng';
$_COS_LANG_MODULE['Replace string'] = 'Erstatt streng';
$_COS_LANG_MODULE['Search and replace'] = 'Søk og erstatt';
$_COS_LANG_MODULE['Key'] = 'Nøkkel';
$_COS_LANG_MODULE['No translation in'] = 'Ingen oversettelse';
$_COS_LANG_MODULE['Translation in'] = 'Oversettelse i';
$_COS_LANG_MODULE['Update'] = 'Refresh';
$_COS_LANG_MODULE['Edit'] = 'Rediger';
$_COS_LANG_MODULE['Timezone has been updated'] = 'Tidssoneoppdatering';
$_COS_LANG_MODULE['Timezone is not valid'] = 'Ikke en gyldig tidssone';
$_COS_LANG_MODULE['Set timezone for your system'] = 'Velg tidssone';
$_COS_LANG_MODULE['Locale has been updated'] = 'Språket har blitt oppdatert';
$_COS_LANG_MODULE['Locale is not valid'] = 'Local ikke gyldig';
$_COS_LANG_MODULE['Set locale. Set e.g. dates and money symbols to your language specifics'] = 'Sett locale - påvirker navnene på slike datoer og penger skilter og forkortelser';
$_COS_LANG_MODULE['Language is not valid'] = 'Ikke en gydigt språk';
$_COS_LANG_MODULE['Set language of interface and HTML document'] = 'Velg språk for grensesnitt';
$_COS_LANG_MODULE['Update all language files (may take a few minutes)'] = 'Update oversettelse (ha tålmodighet)';
$_COS_LANG_MODULE['Reload language_all files from <span class="notranslate">{template}</span> into DB'] = 'Last language_all filer fra <span class="notranslate">{template}</span> i DB';
$_COS_LANG_MODULE['Languages has been reloaded'] = 'Språket har blitt reloaded';
$_COS_LANG_MODULE['DB translation has been updated'] = 'DB oversettelse eh oppdatert';
$_COS_LANG_MODULE['No language has been loaded. Presss button to load'] = 'Ingen språk er lastet. Presss knappen for å laste';
