<?php

$_COS_LANG_MODULE['Timezone has been updated'] = 'Zeitzone wurde aktualisiert';
$_COS_LANG_MODULE['Timezone is not valid'] = 'Zeitzone ist nicht gültig';
$_COS_LANG_MODULE['Set timezone for your system'] = 'Stellen Sie Zeitzone für Ihr System';
$_COS_LANG_MODULE['Locale has been updated'] = 'Locale wurde aktualisiert';
$_COS_LANG_MODULE['Locale is not valid'] = 'Locale ist nicht gültig';
$_COS_LANG_MODULE['Set locale. Set e.g. dates and money symbols to your language specifics'] = 'Stellen Sie locale. Stellen Sie z. B. Termine und Geld Symbole, um Ihre Sprache Besonderheiten';
$_COS_LANG_MODULE['Language is not valid'] = 'Die Sprache ist nicht gültig';
$_COS_LANG_MODULE['Set language of interface and HTML document'] = 'Set Sprache der Schnittstelle und HTML-Dokument';
$_COS_LANG_MODULE['Update all language files (may take a few minutes)'] = 'Aktualisieren Sie alle Sprachdateien (Geduld)';
$_COS_LANG_MODULE['Her er en lille test'] = 'Her er en lille Test';
$_COS_LANG_MODULE['Load language all into DB'] = 'Sprache laden alle in DB';
$_COS_LANG_MODULE['submit'] = 'einreichen';
$_COS_LANG_MODULE['Search and replace in all strings'] = 'Suchen und Ersetzen in alle Strings';
$_COS_LANG_MODULE['Search string'] = 'Suchbegriff';
$_COS_LANG_MODULE['Replace string'] = 'String ersetzen';
$_COS_LANG_MODULE['Search and replace'] = 'Suchen und Ersetzen';
$_COS_LANG_MODULE['Key'] = 'Schlüssel';
$_COS_LANG_MODULE['No translation in'] = 'Keine Übersetzung in';
$_COS_LANG_MODULE['Translation in'] = 'Übersetzung in';
$_COS_LANG_MODULE['Update'] = 'Aktualisierung';
$_COS_LANG_MODULE['Edit'] = 'Bearbeiten';
$_COS_LANG_MODULE['Reload language_all files from <span class="notranslate">{template}</span> into DB'] = 'Language_all neu laden Dateien von <span class="notranslate">{template}</span> in DB';
$_COS_LANG_MODULE['Languages has been reloaded'] = 'Sprachen neu geladen wurde';
$_COS_LANG_MODULE['DB translation has been updated'] = 'DB Übersetzung er aktualisiert';
$_COS_LANG_MODULE['No language has been loaded. Presss button to load'] = 'Keine Sprache geladen wurde. Pressespiegel-Taste, um zu laden';
