<?php

$_COS_LANG_MODULE['Timezone has been updated'] = 'Tidszone er blevet opdateret';
$_COS_LANG_MODULE['Timezone is not valid'] = 'Tidszone er ikke gyldig';
$_COS_LANG_MODULE['Set timezone for your system'] = 'Indstil tidszone for dit system';
$_COS_LANG_MODULE['Locale has been updated'] = 'Locale er blevet opdateret';
$_COS_LANG_MODULE['Locale is not valid'] = 'Locale er ikke gyldig';
$_COS_LANG_MODULE['Set locale. Set e.g. dates and money symbols to your language specifics'] = 'Indstil locale. Sæt fx datoer og penge symboler til din sproglige detaljerne';
$_COS_LANG_MODULE['Language is not valid'] = 'Sprog er ikke gyldig';
$_COS_LANG_MODULE['Set language of interface and HTML document'] = 'Sæt sprog interface og HTML-dokument';
$_COS_LANG_MODULE['Update all language files (may take a few minutes)'] = 'Opdater alle sprogfiler (være patient)';
