<?php

$_COS_LANG_MODULE['Her er en lille test'] = 'Tässä pieni testi';
$_COS_LANG_MODULE['Load language all into DB'] = 'Aseta kieli kaikki osaksi TE';
$_COS_LANG_MODULE['submit'] = 'esittää';
$_COS_LANG_MODULE['Search and replace in all strings'] = 'Etsi ja korvaa kaikki kielet';
$_COS_LANG_MODULE['Search string'] = 'Hakumerkkijonoa';
$_COS_LANG_MODULE['Replace string'] = 'Korvausmerkkijono';
$_COS_LANG_MODULE['Search and replace'] = 'Etsi ja korvaa';
$_COS_LANG_MODULE['Key'] = 'Avain';
$_COS_LANG_MODULE['No translation in'] = 'Ei käännös';
$_COS_LANG_MODULE['Translation in'] = 'Käännös';
$_COS_LANG_MODULE['Update'] = 'Virkistää';
$_COS_LANG_MODULE['Edit'] = 'Muokata';
$_COS_LANG_MODULE['Reload language_all files from <span class="notranslate">{template}</span> into DB'] = 'Reload language_all tiedostoja <span class="notranslate">{template}</span> osaksi TE';
$_COS_LANG_MODULE['Languages has been reloaded'] = 'Kieli on ladattu uudelleen';
$_COS_LANG_MODULE['DB translation has been updated'] = 'DB käännös er päivitetty';
$_COS_LANG_MODULE['No language has been loaded. Presss button to load'] = 'Kieltä ei ladattu. Presss painiketta ladataksesi';
$_COS_LANG_MODULE['Timezone has been updated'] = 'Aikavyöhykepäivitykseen';
$_COS_LANG_MODULE['Timezone is not valid'] = 'Ei kelvollinen aikavyöhyke';
$_COS_LANG_MODULE['Set timezone for your system'] = 'Valitse aikavyöhyke';
$_COS_LANG_MODULE['Locale has been updated'] = 'Kieli on päivitetty';
$_COS_LANG_MODULE['Locale is not valid'] = 'Paikalliset ei kelpaa';
$_COS_LANG_MODULE['Set locale. Set e.g. dates and money symbols to your language specifics'] = 'Aseta maa - vaikuttaa nimet kuten päivämäärät ja rahaa merkkejä ja lyhenteitä';
$_COS_LANG_MODULE['Language is not valid'] = 'Ei gydigt kieli';
$_COS_LANG_MODULE['Set language of interface and HTML document'] = 'Valitse käyttöliittymän kieli';
$_COS_LANG_MODULE['Update all language files (may take a few minutes)'] = 'Update käännös (kärsivällisyyttä)';
