<?php

$_COS_LANG_MODULE['Timezone has been updated'] = 'Tidszon har uppdaterats';
$_COS_LANG_MODULE['Timezone is not valid'] = 'Tidszon är inte giltig';
$_COS_LANG_MODULE['Set timezone for your system'] = 'Ange tidszon för ditt system';
$_COS_LANG_MODULE['Locale has been updated'] = 'Val av språk har uppdaterats';
$_COS_LANG_MODULE['Locale is not valid'] = 'Val av språk är inte giltig';
$_COS_LANG_MODULE['Set locale. Set e.g. dates and money symbols to your language specifics'] = 'Ställ locale. Ställ t.ex. datum och symboler pengar till ditt språk detaljerna';
$_COS_LANG_MODULE['Language is not valid'] = 'Språket är inte giltig';
$_COS_LANG_MODULE['Set language of interface and HTML document'] = 'Ange språk för gränssnitt och HTML-dokument';
$_COS_LANG_MODULE['Update all language files (may take a few minutes)'] = 'Uppdatera alla språkfiler (ha tålamod)';
$_COS_LANG_MODULE['Her er en lille test'] = 'Här är ett litet test';
$_COS_LANG_MODULE['Load language all into DB'] = 'Ladda språk alla i DB';
$_COS_LANG_MODULE['submit'] = 'lämna';
$_COS_LANG_MODULE['Key'] = 'Nyckel';
$_COS_LANG_MODULE['Translation in'] = 'Översättning i';
$_COS_LANG_MODULE['No translation in'] = 'Ingen översättning';
$_COS_LANG_MODULE['Update'] = 'Uppdatera';
$_COS_LANG_MODULE['Edit'] = 'Redigera';
$_COS_LANG_MODULE['Reload language_all files from <span class="notranslate">{template}</span> into DB'] = 'Ladda language_all filer från <span class="notranslate">{template}</span> till DB';
$_COS_LANG_MODULE['Languages has been reloaded'] = 'Språk har reloaded';
$_COS_LANG_MODULE['DB translation was updated'] = 'DB översättning uppdaterades';
$_COS_LANG_MODULE['No language has been loaded. Presss button to load'] = 'Inget språk har laddats. Presss knappen för att ladda';
