<?php

$_COS_LANG_MODULE['locales_timezone_updated'] = 'Tidszon Uppdaterat';
$_COS_LANG_MODULE['locales_timezone_not_valid'] = 'Tidszon är inte giltig';
$_COS_LANG_MODULE['locales_timezone_legend'] = 'Ställ tidszon';
$_COS_LANG_MODULE['locales_locale_updated'] = 'Val av språk har uppdaterats';
$_COS_LANG_MODULE['locales_locale_not_valid'] = 'Val av språk är inte giltig';
$_COS_LANG_MODULE['locales_set_locale_legend'] = 'Ange språk. Ställ t.ex. datum och symboler pengar till ditt språk detaljerna';
$_COS_LANG_MODULE['locales_language_updated'] = 'Språkversioner har uppdaterats';
$_COS_LANG_MODULE['locales_language_not_valid'] = 'Språket är inte giltig';
$_COS_LANG_MODULE['locales_set_language_lengend'] = 'Ange språk för gränssnitt och HTML-dokument';
$_COS_LANG_MODULE['locales_reload_language'] = 'Uppdatera alla språkfiler (ha tålamod)';
